version: 1
disable_existing_loggers: false

formatters:
  uvicorn_default:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(asctime)s - %(levelprefix)s [%(name)s] %(message)s"
    use_colors: None
  simple:
    format: "%(asctime)s - [%(levelname)s] [%(name)s] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    # stream: ext://sys.stdout
    formatter: uvicorn_default
  time_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: "./logs/app.log"
    encoding: utf-8
    backupCount: 10
    # when: 'S'
    when: 'midnight'

loggers:
  uvicorn:
    handlers: [console, time_file]
    level: DEBUG
  app:
    propagate: false
    level: INFO
    handlers: [console, time_file]
